name: Deploy to HostGator

on:
  push:
    branches:
      - main  # Gatilho para o deploy, ao fazer push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copy files to HostGator
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          DIRECTORY: ${{ secrets.DIRECTORY }}
        run: |
          rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ $USERNAME@$HOST:$DIRECTORY

      - name: Run migrations and seeders on HostGator
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          DIRECTORY: ${{ secrets.DIRECTORY }}
        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
            cd $DIRECTORY || exit 1
            composer install
            php artisan down || true
            php artisan optimize:clear
            php artisan migrate:fresh --force
            php artisan db:seed --force
            php artisan db:seed --class=BenefitDeliverySeeder --force
            php artisan optimize:clear
            php artisan up
          EOF
